import Anthropic from '@anthropic-ai/sdk';
import { TAKE_POSITIONS, buildPrompt } from '../lib/perspectives.js';

// ── Pexels photo fetch ────────────────────────────────────────────────────────
async function fetchPexelsPhoto(query) {
  const key = process.env.PEXELS_KEY;
  if (!key) return null;
  try {
    const q = encodeURIComponent(query.slice(0, 80));
    const res = await fetch(
      `https://api.pexels.com/v1/search?query=${q}&per_page=3&orientation=landscape`,
      { headers: { Authorization: key } }
    );
    if (!res.ok) return null;
    const data = await res.json();
    return data.photos?.[0]?.src?.large2x || data.photos?.[0]?.src?.large || null;
  } catch { return null; }
}

// ── Generate a single take via Claude ────────────────────────────────────────
async function generateOneTake(client, topic, meta, language) {
  try {
    const { prompt, derivedSources } = buildPrompt(topic, meta, language);
    const msg = await client.messages.create({
      model:      'claude-haiku-4-5-20251001',
      max_tokens: 500,
      messages:   [{ role: 'user', content: prompt }],
    });
    const text  = msg.content[0]?.text || '';
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) throw new Error('No JSON in response');
    const parsed = JSON.parse(match[0]);
    if (!parsed.take?.text) throw new Error('No take text');
    return {
      ...parsed.take,
      color:   meta.color,
      sources: [{ name: 'AI Analysis — perspectives generated by Claude', framing: null, url: null }],
    };
  } catch {
    // Graceful fallback so one failed take doesn't break the whole card
    return {
      position: meta.position,
      label:    meta.label,
      text:     `A ${meta.label.toLowerCase()} perspective on this topic.`,
      color:    meta.color,
      sources:  [{ name: 'AI Analysis — perspectives generated by Claude', framing: null, url: null }],
    };
  }
}

// ── Handler ───────────────────────────────────────────────────────────────────
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin',  '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST')   return res.status(405).json({ error: 'Method not allowed' });

  if (!process.env.ANTHROPIC_API_KEY)
    return res.status(500).json({ error: 'ANTHROPIC_API_KEY not configured' });

  const { query, language = 'English' } = req.body || {};
  if (!query?.trim()) return res.status(400).json({ error: 'query is required' });

  const cleanQuery = query.trim().slice(0, 200);

  // Build synthetic topic — no real articles, so Claude reasons from its knowledge
  const topic = {
    id:                `ask_${Date.now()}`,
    title:             cleanQuery,
    latestPublishedAt: new Date().toISOString(),
    urlToImage:        null,   // filled below
    category:          'World',
    summary:           null,
    articles:          [],
    perspectiveMode:   'full',
    biasCounts:        {},
    sourceTiers:       null,
    isAskTopic:        true,
  };

  // Fetch photo + generate all 7 takes in parallel
  const [photoUrl, ...takes] = await Promise.all([
    fetchPexelsPhoto(cleanQuery),
    ...TAKE_POSITIONS.map(meta => {
      const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
      return generateOneTake(client, topic, meta, language);
    }),
  ]);

  topic.urlToImage = photoUrl;

  // Build takes map keyed by position integer
  const takesMap = {};
  for (const take of takes) {
    takesMap[take.position] = take;
  }

  return res.json({ topic, takes: takesMap });
}
